## 2.1 环境配置

在开始学习 pytorch 之前， 我们先来学习一下运行 pytorch 的环境，以及 pytorch 的基本用法。

### 2.1.1 Anaconda

#### Anaconda 是什么？

Anaconda 是 Python 的一个开源发行版本，主要面向科学计算。我们可以这样简单地理解，Anaconda是一个预装了很多用到的或用不到的第三方库的 Python。

#### Anaconda 安装

- 第一步： 官网下载 (https://www.anaconda.com)
- 第二步： 安装软件
- 第三步： 测试安装是否成功

```
检测下列软件是否可以正常执行
$ python
$ ipython
$ conda
$ jupyter notebook
```

#### Anaconda 环境管理 

```
$ conda create -name env_name           # 创建新的环境
$ conda activate env_name               # 激活环境
$ conda deactivate                      # 退出环境
$ conda remove env_name --all           # 删除环境
```

#### Anaconda 软件包管理 

```
$ conda list                                  # 查看所有已安装的包
$ conda install package_name                  # 当前环境下安装包
$ conda remove package_name                   # 删除当前环境下包
$ conda install -name env_name package_name   # 指定环境下安装包
$ conda remove -name env_name package_name    # 删除指定环境下安装包
```

#### 常见问题

1. 下载 anaconda 的速度太慢，怎么办？

    可以使用国内清华大学提供的镜像站进行下载。 镜像站的地址为 `https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/`
    

2. 使用 conda 命令安装软件太慢，怎么办？

   可以更换 conda 清华大学的镜像源，操作如下：

```
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
conda config --set show_channel_urls yes
```

### 2.1.2 jupyter

#### jupyter 是什么

Jupyter notebook（http://jupyter.org/） 是一种 Web 应用，能让用户将说明文本、数学方程、代码和可视化内容全部组合到一个易于共享的文档中。

#### 安装使用

- 第一步： 安装 anaconda
- 第二步： 命令行输入 jupyter note
- 第三步： 浏览器打开 http://localhost:8888 

### 2.1.3 pytorch

 ####  安装
 
 - 安装 gpu 版
 
 conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
 
 注：cudatoolkit 是指定机器的 cuda 版本，这个需要根据机器的情况填写不同的版本信息
 
 
 - 安装 cpu 版
 
 conda install pytorch torchvision torchaudio cpuonly -c pytorch

## 2.2 pytorch 数据操作

### 2.2.1 创建 tensor

In [15]:
import torch

# 创建 初始 5x3 矩阵
x = torch.empty(5, 3)

# 创建 随机 5x3 矩阵
x = torch.rand(5, 3)

# 创建 long 型 5x3 零矩形
x = torch.zeros(5, 3, dtype=torch.long)

# 根据数据创建 Tensor
x = torch.tensor([5.01, 6.])

# 返回的tensor默认具有相同的 torch.dtype和torch.device
x = x.new_ones(5, 3, dtype=torch.float64)  

# 指定新的数据类型
x = torch.randn_like(x, dtype=torch.float) 

# 获取数据形状
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


**常用 函数**

| 函数 |功能
| :-- | :--
| Tensor(*sizes) | 基础构造函数
| tensor(data) | 数据类型转换为 tensor
| ones(*sizes)	| 全 1 Tensor
| zeros(*sizes)	| 全 0 Tensor
| eye(*sizes)	| 对角线为 1，其他为 0
| arange(s,e,step) | 从 s 到 e，步长为 step
| linspace(s,e,steps) | 从 s 到 e，均匀切分成 steps 份
| rand/randn(*sizes) | 均匀/标准分布
| normal(mean,std)/uniform(from,to) | 正态分布/均匀分布
| randperm(m) | 随机排列

### 2.2.2 操作 tensor

#### 算术操作

In [17]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
result = torch.empty(5, 3)

# 加法形式一
x + y

# 加法形式二
torch.add(x, y, out = result)

# 加法形式三 -> inplace
y = y.add_(x)

#### 索引

索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。

In [3]:
y = x[0, :]

**常用函数**

| 函数 | 功能
| :-- | :--|
| index_select(input, dim, index) | 在指定维度 dim 上选取，比如选取某些行、某些列
| masked_select(input, mask) | 例子如上，a[a>0]，使用 ByteTensor 进行选取
| nonzero(input) | 非0元素的下标
| gather(input, dim, index) | 根据 index，在 dim 维度上选取数据，输出的 size 与 index 一样

#### 改变形状

In [4]:
# view 改变形状，也共享内存
# 注意 view() 返回的新 Tensor 与源 Tensor 虽然可能有不同的 size，
# 但是是共享 data 的，也即更改其中的一个，另外一个也会跟着改变。
# (顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)
y = x.view(15)

# 使用 clone() 可以创建新副本， 不共享 data
z = x.clone().view(15)

In [5]:
# 函数就是item(), 可以将一个标量 Tensor 转换成一个 Python number
z = torch.rand(1)
z.item()

0.8247038722038269

#### 线性代数

| 函数 | 功能
| :-- | :-- |
| trace | 对角线元素之和 ( 矩阵的迹 )
| diag | 对角线元素
| triu | 矩阵的上三角，可指定偏移量
| tril | 矩阵的下三角，可指定偏移量
| mm | 矩阵乘法
| bmm | batch 的矩阵乘法
| addmm/addbmm/addmv/addr/baddbmm..| 矩阵运算
| t | 转置
| dot/cross | 内积/外积
| inverse | 求逆矩阵
| svd | 奇异值分解

### 2.2.3 广播机制

当对两个形状不同的 Tensor 按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个 Tensor 形状相同后再按元素运算。也就是自动补充数据的机制

In [6]:
x = torch.arange(1, 3).view(1, 2)
y = torch.arange(1, 4).view(3, 1)
x + y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

### 2.2.4 运算的内存开销

In [35]:
# 索引操作是不会开辟新内存的，而像 y = x + y 这样的运算是会新开内存的，然后将y指向新内存
id_before = id(y)
y = y + x
print(id(y) == id_before) # False 

# 如果想指定结果到原来的 y 的内存，我们可以使用索引来进行替换操作
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True

# 还可以使用运算符全名函数中的 out 参数或者 自加运算符+=( 也即add_())达到上述效果
id_before = id(y)
torch.add(x, y, out=y)
print(id(y) == id_before) # True

id_before = id(y)
y += x
print(id(y) == id_before) # True

id_before = id(y)
y.add_(x)
print(id(y) == id_before) # True

False
True
True
True
True


### 2.2.5 Tensor 和 Numpy 的互换

- numpy() 将 Tensor 转成 Numpy 数组
- from_numpy() 将 Numpy 数组转成 Tensor

这两个函数所产生的的 Tensor 和 Numpy 中的数组共享相同的内存，改变其中一个时另一个也会改变

In [7]:
import numpy as np

# Tensor -> Numpy
a = torch.ones(5)
b = a.numpy()

# Numpy -> Tensor
a = np.ones(5)
b = torch.from_numpy(a)

此外还有一个常用的方法就是直接用 torch.tensor() 将 Numpy 数组转换成 Tensor，需要注意的是该方法总是会进行数据拷贝，返回的 Tensor 和原来的数据不再共享内存。

In [8]:
c = torch.tensor(a)
a += 1

### 2.2.6 Tensor On GPU

用方法 to() 可以将 Tensor 在 CPU 和 GPU 之间相互移动

In [10]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在 GPU 上的 Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    z.to("cpu", torch.double)              # to()还可以同时更改数据类型

## 2.3 自动求梯度

PyTorch 提供的 autograd 包能够根据输入和**前向传播**过程自动构建计算图，并执行**反向传播**

### 2.3.1 概念

1. 求梯度

- 将 Tensor 属性 .requires_grad 设置为 True，将开始追踪在其上的所有操作（这样就可以利用链式法则进行梯度传播了）
- 调用 .backward() 完成所有梯度计算， Tensor 的梯度将累积到 .grad 属性中
- .backward() 时，如果 y 是标量，则不需要为 backward() 传入任何参数；否则，需要传入一个与 y 同形的 Tensor

2. 取消梯度

- 调用 .detach(), 取消跟踪，防止将来的计算被追踪
- 可用 with torch.no_grad() 将不想被追踪的操作代码块包裹起来，这种方法在评估模型的时候很常用。
- 也可 设置 requires_grad = False 取消梯度。

3. 计算函数
- Tensor 和 Function 互相结合就可构建一个记录有整个计算过程的有向无环图（DAG）。
- Tensor 有一个 .grad_fn 属性，该属性即创建该 Tensor 的 Function。
- 就是说该 Tensor 是不是通过某些运算得到的，若是，则 grad_fn 返回一个与这些运算相关的对象，否则是 None。

### 2.3.2 Tensor

设置 requires_grad

In [11]:
# 设置 requires_grad
x = torch.ones(2, 2, requires_grad = True)
print(x.grad_fn)

y = x + 2
print(y.grad_fn)

None


通过 .requires_grad_() 来用 in-place 的方式改变 requires_grad 属性

In [12]:
a = torch.randn(2, 2) # 缺失情况下默认 requires_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad) # False
a.requires_grad_(True)
print(a.requires_grad) # True
b = (a * a).sum()
print(b.grad_fn)

False
True


### 2.3.3 梯度

在 y.backward() 时，如果 y 是标量，则不需要为 backward() 传入任何参数；否则，需要传入一个与 y 同形的 Tensor 

In [84]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
# m 是标量， backward() 不传入任何参数
m = y.mean()
m.backward()
print(x.grad)

y = 2 * x
# z 不是是标量， backward() 需要传入 y 同形的 Tensor
z = y.view(2, 2)
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([0.5000, 0.5000, 0.5000, 0.5000])
tensor([2.5000, 0.7000, 0.5200, 0.5020])


grad 在反向传播过程中是累加的，这意味着每一次运行反向传播，梯度都会累加之前的梯度，所以一般在反向传播之前需把梯度清零。

In [85]:
# 再来反向传播一次，注意grad是累加的
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
# grad 一定要清零
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([3.5000, 1.7000, 1.5200, 1.5020])
tensor([1., 1., 1., 1.])


中断梯度追踪的例子

In [86]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2
# 取消求梯度
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad) # True
print(y2, y2.requires_grad) # Falsebb
print(y3, y3.requires_grad) # True

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


为什么是 $y_3$ 的导数是 2 呢？$y_3 = y_1 + y_2 = x^2 + x^3$，当 $x = 1$ 时 $\frac{dy_3}{dx}$ 不应该是 5 吗？事实上，由于 $y_2$ 的定义是被 torch.no_grad() 包裹的，所以与 $y_2$ 有关的梯度是不会回传的，只有与 $y_1$ 有关的梯度才会回传，即 $x_2$ 对 $x$ 的梯度。

如果我们想要修改 tensor 的数值，但是又不希望被 autograd 记录（即不会影响反向传播），那么我么可以对 tensor.data 进行操作

In [88]:
x = torch.ones(1, requires_grad=True)

print(x.data) # 还是一个tensor
print(x.data.requires_grad) # 但是已经是独立于计算图之外

y = x * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x) # 更改data的值也会影响tensor的值
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([200.])
